#!/bin/bash

if [ -t 0 ]
 then

  TARGET=$(terraform output|grep "mesos-master-lb"|awk '{print $3}')
  CONFIG=/tmp/cimesos.toml

  cat << EOF >$CONFIG
[core]
dcos_url = "http://${TARGET}"
reporting = false
token = "b12eca6fc0b7d82eedf58e832e941416376ca7e24db3cf8f03e9efe8e0903b7c"
mesos_master_url = "http://${TARGET}:5050"
timeout = 5
ssl_verify = "false"
email = "youremail@dot.com"
[marathon]
url = "http://${TARGET}:8080"
[package]
sources = [ "https://github.com/mesosphere/multiverse/archive/version-1.x.zip", "https://universe.mesosphere.com/repo",]
cache = "/Users/nixlike/.dcos/cache"
EOF

  DCOS_CONFIG=$CONFIG dcos "$@"

 else
  input="-"
  json=$(cat $input)
  export json
  DCOS_CONFIG=$CONFIG echo "$json" | dcos "$@"
fi
